[package]
name = "scurl"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.22", features = ["blocking", "rustls-tls"] }
clap = { version = "4.2", features = ["derive"] }
anyhow = { version="1.0" }
