name: Build and Release scurl

on:
  push:
    tags:
      - 'v*.*.*'     # Only runs on version tags like v1.0.0
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build binary
        run: cargo build --release

      - name: Rename binary
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            mv target/release/scurl.exe scurl-windows.exe
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            mv target/release/scurl scurl-macos
          else
            mv target/release/scurl scurl-linux
          fi
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scurl-${{ matrix.os }}
          path: scurl-*